name: Jenkins-AutoTesting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # This allows triggering via the GitHub API.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdfkit

    - name: Run Flake8
      run: |
        source venv/bin/activate
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Pytest and generate reports
      run: |
        source venv/bin/activate
        pytest --junitxml=test-results.xml --html=test-results.html --self-contained-html

    - name: Convert HTML to PDF
      run: |
        source venv/bin/activate
        python3 -c "import pdfkit; pdfkit.from_file('test-results.html', 'test-results.pdf')"

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          test-results.xml
          test-results.html
          test-results.pdf
